FROM fedora:32@sha256:7afb459893c1c5defb714d7e0a2aae4a5c2a12f24aa5b26ff5f8f8e7dd8b2317 as base
WORKDIR /root
COPY ./tools/fedora37_deps.sh ./tools/deps.sh
COPY ./tools/requirements.txt /requirements.txt
RUN ./tools/deps.sh

FROM base AS buildergcc
COPY ./tools ./tools
RUN mkdir -p /prebuild/gcc
RUN ./tools/builddeps.sh --gcc --prefix /prebuild/gcc

FROM base AS builderclang
COPY ./tools ./tools
RUN mkdir -p /prebuild/clang
RUN ./tools/builddeps.sh --clang --prefix /prebuild/clang

FROM base
COPY --from=buildergcc /prebuild/gcc /prebuild/gcc
COPY --from=builderclang /prebuild/clang /prebuild/clang

RUN chmod +xr /root
WORKDIR /root/gdk
VOLUME /root/gdk
