FROM ubuntu:20.04@sha256:bffb6799d706144f263f4b91e1226745ffb5643ea0ea89c2f709208e8d70c999 as base
WORKDIR /root
COPY ./tools/ubuntu_20.04_deps.sh ./tools/deps.sh
COPY ./tools/requirements.txt /requirements.txt
COPY ./cmake/profiles/ ./cmake/profiles/
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
RUN ./tools/deps.sh

FROM base AS buildergcc
COPY ./tools ./tools
RUN mkdir -p /prebuild/gcc
RUN ./tools/builddeps.sh --gcc --prefix /prebuild/gcc

FROM base AS builderclang
COPY ./tools ./tools
RUN mkdir -p /prebuild/clang
RUN ./tools/builddeps.sh --clang --prefix /prebuild/clang

FROM base
COPY --from=buildergcc /prebuild/gcc /prebuild/gcc
COPY --from=builderclang /prebuild/clang /prebuild/clang

RUN chmod +xr /root
WORKDIR /root/gdk
VOLUME /root/gdk
