FROM fedora:30@sha256:0fed6e62cc914f574f0d221cbce4ce58c8105a0be942f221a14f38aaa75fac6f
COPY fedora30_deps.sh /deps.sh
COPY requirements.txt /requirements.txt
RUN /deps.sh && rm /deps.sh
CMD cd /sdk && ./tools/build.sh --clang

